<?xml version="1.0" encoding="utf-8"?><Database Name="BugTrackingSystem" Class="DataClassesBugTrackingSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WIN-PUPMJZP05MP\SQLEXPRESS;Initial Catalog=BugTrackingSystem;Integrated Security=True" SettingsObjectName="Data.Properties.Settings" SettingsPropertyName="BugTrackingSystemConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bugs" Member="Bugs">
    <Type Name="Bug">
      <Column Name="BugId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TesterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Association Name="Project_Bug" Member="Project" ThisKey="ProjectId" OtherKey="ProjectId" Type="Project" IsForeignKey="true" />
      <Association Name="Tester_Bug" Member="Tester" ThisKey="TesterId" OtherKey="TesterId" Type="Tester" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="ProjectId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="Project_Bug" Member="Bugs" ThisKey="ProjectId" OtherKey="ProjectId" Type="Bug" />
    </Type>
  </Table>
  <Table Name="dbo.Testers" Member="Testers">
    <Type Name="Tester">
      <Column Name="TesterId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(62) NOT NULL" CanBeNull="false" />
      <Column Name="LastAction" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="Tester_Bug" Member="Bugs" ThisKey="TesterId" OtherKey="TesterId" Type="Bug" />
    </Type>
  </Table>
</Database>